### ISSUE TITLE
Invalid syntax  in def clear_params

### ISSUE THREAD

**Issue by pidzej** [lucasheld/ansible-uptime-kuma#21]
Uptime Kuma: 1.21.2
Ansible:  2.10.7

Hi when i try use playbook like this:
```
- hosts: ansible
  tasks:
    - name: Login by token and create a monitor
      lucasheld.uptime_kuma.monitor:
        api_url: http://192.168.10.25:3001
        api_username: admin
        api_password: secret123
        name: Goojkhgle
        type: http
        url: https://google.com
        state: present
```

Error in output:

```
TASK [Login by token and create a monitor] ******************************************************************
task path: /home/ansible/ansible_dir/playbooks/uptimekuma.yml:3
<ansible> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<ansible> EXEC /bin/sh -c 'echo ~ansible && sleep 0'
<ansible> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp `"&& mkdir "` echo /home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787 `" && echo ansible-tmp-1681983688.5391455-59112-150114658119787="` echo /home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787 `" ) && sleep 0'
Using module file /home/ansible/.ansible/collections/ansible_collections/lucasheld/uptime_kuma/plugins/modules/monitor.py
<ansible> PUT /home/ansible/.ansible/tmp/ansible-local-590185knhddhd/tmp5m13g9jk TO /home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/AnsiballZ_monitor.py
<ansible> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/ /home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/AnsiballZ_monitor.py && sleep 0'
<ansible> EXEC /bin/sh -c '/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/AnsiballZ_monitor.py && sleep 0'
<ansible> EXEC /bin/sh -c 'rm -f -r /home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/AnsiballZ_monitor.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/AnsiballZ_monitor.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/AnsiballZ_monitor.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.lucasheld.uptime_kuma.plugins.modules.monitor', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_lucasheld.uptime_kuma.monitor_payload_TtsHb4/ansible_lucasheld.uptime_kuma.monitor_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/monitor.py", line 291, in <module>
  File "/tmp/ansible_lucasheld.uptime_kuma.monitor_payload_TtsHb4/ansible_lucasheld.uptime_kuma.monitor_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/module_utils/common.py", line 39
    def clear_params(params: dict):
                           ^
SyntaxError: invalid syntax
fatal: [ansible]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/AnsiballZ_monitor.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/AnsiballZ_monitor.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1681983688.5391455-59112-150114658119787/AnsiballZ_monitor.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.lucasheld.uptime_kuma.plugins.modules.monitor', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_lucasheld.uptime_kuma.monitor_payload_TtsHb4/ansible_lucasheld.uptime_kuma.monitor_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/modules/monitor.py\", line 291, in <module>\n  File \"/tmp/ansible_lucasheld.uptime_kuma.monitor_payload_TtsHb4/ansible_lucasheld.uptime_kuma.monitor_payload.zip/ansible_collections/lucasheld/uptime_kuma/plugins/module_utils/common.py\", line 39\n    def clear_params(params: dict):\n                           ^\nSyntaxError: invalid syntax\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by lucasheld** [comment]
You are using Python version 2.7, but this collection requires Python version 3.6+ as described in the readme.
